### ISSUE TITLE
Load Model NoneType Error

### ISSUE THREAD

**Issue by getshaun24** [strongio/keras-elmo#11]
Hii,

When I try and load the model I get always get a NoneType error.
I assume this means that the model is not loading properly.
I have tried saving the model architecture and the weights both separately and together. 

The only difference in my code and this one (with the corresponding output shape mod) is that I am using the ['elmo'] param instead of ['default'].

Any suggestions ??!

**Comment by Simaex** [comment]
If you are referencing the next code please check that you have defined signature 'elmo' that you try to use. Original ELMO model do not have such signature defined.
`def call(self, x, mask=None):
        result = self.elmo(K.squeeze(K.cast(x, tf.string), axis=1),
                      as_dict=True,
                      signature='default',
                      )['default']
        return result`
