### ISSUE TITLE
AttributeError: module 'keras.backend' has no attribute 'tf'

### ISSUE THREAD

**Issue by elsheikh21** [strongio/keras-elmo#17]
```self._trainable_weights += K.tf.trainable_variables( ```
AttributeError: module 'keras.backend' has no attribute 'tf'

Python '3.6.4'
Tensorflow '1.12.0'
Keras '2.2.5'

**Comment by elsheikh21** [comment]
The solution is:

```
import tensorflow as tf
import tensorflow.keras.backend as B
import tensorflow_hub as hub
from tensorflow.python.keras.engine import Layer
```

and 

```self._trainable_weights += tf.trainable_variables( ```

**Comment by Balaje-BITS** [comment]
from keras import backend as K
tf = K.tensorflow_backend.tf

I have fixed the error by placing the above code.
