### ISSUE TITLE
Could we use keras-elmo module on other language?

### ISSUE THREAD

**Issue by pingchesu** [strongio/keras-elmo#5]
Really appreciate for sharing. I have one question is that could the keras-elmo module use other languages as input or keras-elmo is only for english NLP problems?

**Comment by juharris** [comment]
The TensorFlow Hub module used by this project is just for English but if you'd like to train your own for another language then you should see https://github.com/allenai/bilm-tf

**Comment by jacobzweig** [comment]
Correct @juharris – you might have more luck with BERT (see https://github.com/strongio/keras-bert)
