### ISSUE TITLE
Should use ELMO version 2 from lab

### ISSUE THREAD

**Issue by PhilipMay** [strongio/keras-elmo#6]
There is a version 2 of ELMO in TF lab. See here:
https://www.tensorflow.org/hub/modules/google/elmo/2

You maybe want to use this instead.

https://github.com/strongio/keras-elmo/blob/9726d2cfa6433ff7147fa17a312cce78a760561f/Elmo%20Keras.ipynb#L153

**Comment by jacobzweig** [comment]
Thanks for the suggestion @PhilipMay – the notebook has been updated to the version 2.
