### ISSUE TITLE
Weights are not trainable.

### ISSUE THREAD

**Issue by juharris** [strongio/keras-elmo#7]
The weights need to be registered as trainable weights for Keras.

Solution:
```
import tensorflow_hub as hub
from keras import backend as K
from keras.engine import Layer

class ElmoEmbeddingLayer(Layer):
    def __init__(self, **kwargs):
        self.dimensions = 1024
        super(ElmoEmbeddingLayer, self).__init__(trainable=True, **kwargs)

    def build(self, input_shape):
        self.elmo = hub.Module('https://tfhub.dev/google/elmo/2', trainable=self.embed_trainable,
                               name="{}_module".format(self.name))

        self.trainable_weights += K.tf.trainable_variables(scope="^{}_module/.*".format(self.name))
        super(ElmoEmbeddingLayer, self).build(input_shape)

    def call(self, x, mask=None):
        lengths = K.cast(K.argmax(K.cast(K.equal(x, '--PAD--'), 'uint8')), 'int32')
        result = self.elmo(inputs=dict(tokens=x, sequence_len=lengths),
                      as_dict=True,
                      signature='tokens',
                      )['elmo']
        return result

    def compute_mask(self, inputs, mask=None):
        return K.not_equal(inputs, '--PAD--')

    def compute_output_shape(self, input_shape):
        return input_shape + (self.dimensions,)
```

**Comment by jacobzweig** [comment]
Thanks for the suggestion! I've updated the notebook to reflect this.

**Comment by zmjjmz** [comment]
Quick note: If you're a chump like me who for some reason is going through the Keras Model -> Estimator -> `train_and_evaluate` route, the `build` step is called whenever the `model_fn` is called, and Keras won't let you set `trainable_weights` again. I've had success (a training model!) so far by just catching the resultant `AttributeError` and doing nothing w/it.

**Comment by Abhijit-2592** [comment]
@juharris tf.keras doesn't allow setting self.trainable_weights. It is set as a read only parameter. see [here](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer). Any work arounds for that?

**Comment by vondersam** [comment]
What is the reason why the

> The weights need to be registered as trainable weights for Keras.
> 
> Solution:
> 
> ```
> import tensorflow_hub as hub
> from keras import backend as K
> from keras.engine import Layer
> 
> class ElmoEmbeddingLayer(Layer):
>     def __init__(self, **kwargs):
>         self.dimensions = 1024
>         super(ElmoEmbeddingLayer, self).__init__(trainable=True, **kwargs)
> 
>     def build(self, input_shape):
>         self.elmo = hub.Module('https://tfhub.dev/google/elmo/2', trainable=self.embed_trainable,
>                                name="{}_module".format(self.name))
> 
>         self.trainable_weights += K.tf.trainable_variables(scope="^{}_module/.*".format(self.name))
>         super(ElmoEmbeddingLayer, self).build(input_shape)
> 
>     def call(self, x, mask=None):
>         lengths = K.cast(K.argmax(K.cast(K.equal(x, '--PAD--'), 'uint8')), 'int32')
>         result = self.elmo(inputs=dict(tokens=x, sequence_len=lengths),
>                       as_dict=True,
>                       signature='tokens',
>                       )['elmo']
>         return result
> 
>     def compute_mask(self, inputs, mask=None):
>         return K.not_equal(inputs, '--PAD--')
> 
>     def compute_output_shape(self, input_shape):
>         return input_shape + (self.dimensions,)
> ```

Why do the embeddings need to be registered as trainable? Doesn't that depend on whether the person training wants to use the original pre-trained embeddings untouched or not?
